# Generated by Django 5.2.7 on 2026-02-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shohojit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
