# Generated by Django 5.2.7 on 2026-03-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shohojit', '0002_remove_course_course_highlight_coursehighlight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
