# Generated by Django 5.2.7 on 2026-02-15 16:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shohojit', '0002_slider_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_us',
            new_name='AboutUs',
        ),
        migrations.RenameModel(
            old_name='gallery_category',
            new_name='GalleryCategory',
        ),
        migrations.RenameModel(
            old_name='gallery_images',
            new_name='GalleryImages',
        ),
        migrations.RenameModel(
            old_name='our_mission',
            new_name='OurMission',
        ),
        migrations.RenameModel(
            old_name='team_category',
            new_name='TeamCategory',
        ),
        migrations.RenameModel(
            old_name='team_members',
            new_name='TeamMembers',
        ),
        migrations.RenameModel(
            old_name='testimonials_images',
            new_name='TestimonialsImages',
        ),
    ]
