# Generated by Django 5.2.7 on 2026-02-15 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shohojit', '0003_rename_about_us_aboutus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='service_id',
        ),
        migrations.AddField(
            model_name='messages',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='shohojit.service'),
        ),
    ]
