# Generated by Django 5.2.7 on 2026-02-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shohojit', '0004_remove_messages_service_id_messages_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
