# Generated by Django 5.2.7 on 2026-02-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shohojit', '0006_ourjourney_delete_ourmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourjourney',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
