# Generated by Django 5.2.7 on 2026-02-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shohojit', '0007_alter_ourjourney_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourjourney',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ourjourney',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
