# Generated by Django 5.2.7 on 2026-02-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shohojit', '0008_alter_ourjourney_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='vission',
            new_name='vision',
        ),
    ]
